title: Caitlyn Spinuzza # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Junior Android Developer
  <br><br>
  Currently open to work in Hernando County, FL or remote
  <br><br>
  <a href="https://www.linkedin.com/in/caitlyn-spinuzza/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
